apiVersion: v2
name: datahub-prerequisites
description: A Helm chart for packages that Datahub depends on
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.18
dependencies:
  - name: common
    version: 2.9.0
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  # This chart deploys an enterprise version of neo4j that requires commercial license
  - name: neo4j
    version: 4.2.2-1
    repository: https://neo4j-contrib.github.io/neo4j-helm/
    condition: neo4j.enabled
  # This chart deploys a community version of neo4j
  - name: neo4j-community
    version: 1.2.5
    repository: https://equinor.github.io/helm-charts/charts/
    condition: neo4j-community.enabled
  - name: mysql
    version: 9.11.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mysql.enabled
  - name: postgresql
    version: 12.8.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: gcloud-sqlproxy
    version: 0.24.1
    repository: https://charts.rimusz.net
    condition: gcloud-sqlproxy.enabled
  # This chart deploys an enterprise version of kafka that requires commercial license
  # Note, Schema registry and kafka rest proxy do not require the commercial license
  - name: cp-helm-charts
    version: 0.6.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: cp-helm-charts.enabled
  # This chart deploys a community version of kafka
  - name: kafka
    version: 23.0.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kafka.enabled
  # - name: schema-registry
  #   version: 13.0.5
  #   repository: oci://registry-1.docker.io/bitnamicharts
  #   condition: kafka.enabled
maintainers:
  - name: DataHub
    email: datahub@acryl.io
